### ISSUE TITLE
Windows 2000 Server: No mapping between account names and security IDs was done.

### ISSUE THREAD

**Issue by Miuccia7** [LegacyUpdate/LegacyUpdate#159]
Hello,

Running a fresh installation of Windows 2000 Server with Service Pack 4 inside VirtualBox with Guest Additions installed. The SP4 was already part of the OEM installation disk.

After running the first phase of the Legacy Update setup (installing IE6, updating root certificates, etc, couple of reboots) I can't get it to run anymore. After clicking the shortcut in the start menu, a popup arrises with the message "No mapping between account names and security IDs was done". After clicking OK, nothing happens. I tried to reinstall but no luck.

I'm currently logged in as the Administrator user.

![w2kupdate](https://github.com/kirb/LegacyUpdate/assets/86433379/b4124c7c-30da-4b6b-9a85-d6865a0f204e)

![users](https://github.com/kirb/LegacyUpdate/assets/86433379/80ff4bfb-38f8-494d-ac88-29ec87440841)

![w2ksoftware](https://github.com/kirb/LegacyUpdate/assets/86433379/1d4476c0-fa78-4bbb-9b94-d3d75ea4f7f6)

**Comment by kirb** [comment]
Not sure why this is happening exactly, but restarting Windows will fix this. Will keep this open as a reminder to investigate. Most likely I'll just have Legacy Update do a restart rather than log off at the end on Windows 2000.

**Comment by kirb** [comment]
This *may* be fixed by the upcoming Legacy Update 1.10. Haven’t tested yet, but I have a feeling other changes have fixed it as a side-effect (see #208 for more info).

**Comment by kirb** [comment]
Considering this likely fixed in 1.10. Feel free to comment or reopen this if it shows up again.
