### ISSUE TITLE
Broken layout on low-resolution device (XP Tablet PC Edition)

### ISSUE THREAD

**Issue by thepwrtank18** [LegacyUpdate/LegacyUpdate#167]
This is a 800x480 display. Sorry about a phone being used rather than screenshots, I don't know how to do a screenshot on XP.

![image](https://github.com/kirb/LegacyUpdate/assets/57580668/74da2299-3fcb-412b-9765-94983cb90aa4)

![image](https://github.com/kirb/LegacyUpdate/assets/57580668/e5bdfaf2-2674-4078-8c9e-ff2838a578db)

**Comment by kirb** [comment]
Interesting that your install of IE seems to be missing a few components, such as the DirectX and VML features that are used for some of the layout (gradients, and fixing the grey background behind PNGs). Could be XP Tablet PC Edition specific, maybe they're configured to be disabled on battery? As silly as it sounds, try plugging in your tablet and see if it makes a difference.

**Comment by thepwrtank18** [comment]
It was plugged in when the photos were taken.

**Comment by kirb** [comment]
Hi @thepwrtank18! Is this still happening for you?

**Comment by thepwrtank18** [comment]
Can't really tell, the device crapped itself. xD
