### ISSUE TITLE
Windows Update Agent fails to install Error code: 82

### ISSUE THREAD

**Issue by KoleckOLP** [LegacyUpdate/LegacyUpdate#18]
![EeePC](https://media.discordapp.net/attachments/260113652760313866/1045012563836018768/IMG_20221123_172343.jpg)

Legacy Update fails to install on my EeePC 1001HA with the original Czech Windows XP SP3 restored from the recovery media.

**Comment by KoleckOLP** [comment]
I actually fixed it by using files from this site: http://i430vx.net/files/wsusstuff/
I installed rootsupd.exe and WindowsUpdateAgent30-x86.exe

**Comment by Kilroy93** [comment]
I have the same problem on a fresh install of Windows XP Home SP3 OEM (from a retail ISO image, where I changed the ini file to use the PC's OEM key). I installed both rootsupd.exe and WindowsUpdateAgent30-x86.exe but it still gives me error 82

**Comment by KoleckOLP** [comment]
It seems that it's not only a problem of XP even windows 2000 some update needs to be installed manually in order to Legacyupdate to work.
Would be cool if Legacy update told us what update to get or even download it for us.
