### ISSUE TITLE
1.8 Setup not starting in Windows XP x64

### ISSUE THREAD

**Issue by jeanluc162** [LegacyUpdate/LegacyUpdate#185]
Hello, I'm unsure what causes this, but the new Release can't be installed on my Windows XP x64 System. There is no error message, the setup just doesn't open itself.
The previous version still installs & runs fine. This occured on a clean and fresh install of Windows XP x64 Pro, no custom ISO or any funny business of the sort.

### Discussed in https://github.com/kirb/LegacyUpdate/discussions/184

<div type='discussions-op-text'>

<sup>Originally posted by **kirb** October  4, 2023</sup>
* Legacy Update is now signed, so you won’t see any more scary warnings about “program from an unknown publisher” or similar.  
  **Code signing certificates are expensive - this cost me $340 USD. I was only able to do this thanks to those who generously support the project on [GitHub Sponsors](https://github.com/sponsors/kirb) and [Patreon](https://www.patreon.com/adamdemasi).**
* Legacy Update can now be directly accessed from a regular, non-administrator instance of Internet Explorer on Windows Vista and later. This also means you can use Legacy Update via Internet Explorer Mode in Microsoft Edge.
* Provides better messaging when Internet Explorer has been uninstalled (such as in “E” editions of Windows).
* Fixes Legacy Update setup unnecessarily redownloading updates that are already installed.
* Fixes an error when attempting to uninstall Legacy Update from the Control Panel.
* Hopefully fixes the “Enable Microsoft Update” option in Legacy Update setup not working on Windows 7.

<hr /><em>This discussion was created from the release <a href='https://github.com/kirb/LegacyUpdate/releases/tag/v1.8.0.0'>1.8</a>.</em></div>

**Comment by jeanluc162** [comment]
After getting the System up-to-date using the previous version of legacy update, the latest Version could now be installed but I have no idea as to which particular update brought about this change.

**Comment by shit-ware** [comment]
I have the same issue with the latest version on XP Media Center. I downloaded and ran 1.7.1 and it seemed to run without issue.

**Comment by jeanluc162** [comment]
On Server 2008 R2 the installation starts as expected, but during the second stage of the install (after the PC reboots and logs into the temporary user) it crashes. 1.7.1 works just fine there as well.

**Comment by HamNCheeseBorger** [comment]
I have the same issue regarding a fresh install of Windows XP SP1 x86. Legit copy of windows (I have my own CD) on real hardware.

**Comment by kirb** [comment]
Haven't seen this issue in a while (1.9 and 1.10 seem to not have this issue reported) so closing.
