### ISSUE TITLE
Version 1.8 not starting up on fresh install of Windows XP

### ISSUE THREAD

**Issue by HamNCheeseBorger** [LegacyUpdate/LegacyUpdate#191]
I just installed Windows XP on a machine I have. Version is Windows XP SP1 x86, installed using a genuine copy of windows (I have a retail box I purchased a while back). I will try the previous version to see if it will run,

Summary: Version 1.8 simply just has the hourglass icon next to the cursor for about 30 seconds then goes away doing nothing.

**Comment by HamNCheeseBorger** [comment]
So for anyone else having this issue I guess just use 1.7.1 seemed to work for me

**Comment by Miuccia7** [comment]
Same here with Windows Server 2003 SP2, fresh install (EN). Installer won't start. Tested under the Administrator account.

**Comment by TheRealSonicFan** [comment]
I tried running 1.8 on Windows XP SP2 x86 and found it work. I guess maybe 1.8 has an issue on SP1?

**Comment by kirb** [comment]
The issue was likely that the CPU being used doesn't support SSE instructions, which was accidentally required by Legacy Update 1.8 - 1.9. Fixed in 1.10. If you still have problems running Legacy Update, please create a new issue.
