### ISSUE TITLE
Microsoft Security Essentials for Windows XP - Virus and spyware definitions couldn't be updated.

### ISSUE THREAD

**Issue by J0r2** [LegacyUpdate/LegacyUpdate#199]
I downloaded the Windows XP Home Edition ISO from archive.org and just downloaded Legacy Update and installed around 250 updates. I found an error during Microsoft Security Essentials testing.

I have this Windows XP SP3 Version right here:

![Windows XP SP3 Build](https://github.com/kirb/LegacyUpdate/assets/43591096/8ebdc67f-5d26-439a-891d-e8735da6fe11)

I'm having trouble testing Microsoft Security Essentials for Windows XP. I want to test him for nostalgic purposes (I know that this software can't compete with any newer anti-malware solution or with [Windows Defender for Windows 11](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/next-generation-protection)), but I only want to see all the settings available at the time.

This is the error that I encountered:

![Microsoft Security Essentials - Error code 0x80072efe](https://github.com/kirb/LegacyUpdate/assets/43591096/6b9f7249-9a27-401b-a5bd-b855b9ca3570)

As mentioned in Error Reference on Legacy Update, the connection was terminated; maybe this service was shut down too.

![Error Reference - 0x80072efe](https://github.com/kirb/LegacyUpdate/assets/43591096/df3c6e6a-dbc7-4408-b3f9-067004750532)
 
Are there any fixes or workarounds for this issue?

Note: I am using version 1.8 of Legacy Update.

![LegacyUpdate-1 8](https://github.com/kirb/LegacyUpdate/assets/43591096/98d341c8-2cd7-48fe-87c9-35c165dcc7f1)

**Comment by MatiHalek** [comment]
This was noted on Legacy Update website: [https://legacyupdate.net/faq/issues](https://legacyupdate.net/faq/issues): "Attempting to update Microsoft Security Essentials on Windows XP or Vista will display an error message with code 0x80072EFE - “The definition updates couldn't be installed. Please try again later.” Instead, you will need to manually download and install the final definition update that supported these versions". There are also links to download these definitions. 

On Windows Vista, there is a workaround with older version of MSE and update for Server 2008 which allows to have MSE up to date. but I think it's not possible on Windows XP.

**Comment by stdin82** [comment]
```
am_engine.exe　(mpengine.dll 1.1.15800.1)
http://download.windowsupdate.com/c/msdownload/update/software/defu/2019/03/am_engine_8f724ad2cd892ac96c198a474c26b5286eb39968.exe

am_base.exe (mpavbase.vdm 1.293.0.0, mpasbase.vdm 1.293.0.0)
http://download.windowsupdate.com/c/msdownload/update/software/defu/2019/04/am_base_79107b9cc047ccd6baa10e27385f9814c89ed4ab.exe

am_delta.exe (mpavdlta.vdm 1.293.2807.0, mpasdlta.vdm 1.293.2807.0)
http://download.windowsupdate.com/d/msdownload/update/software/defu/2019/06/am_delta_69bbd43267331aa1617813bda17a8ff191b35b21.exe
```

install them in order
or extract the dll/vdm files and move to `"%AllUsersProfile%\Application Data\Microsoft\Microsoft Antimalware\Definition Updates\Updates"` and restart MSE

**Comment by andika207** [comment]
> install them in order 
what are you trying to share ? the first link is dead....

**Comment by andika207** [comment]
> install them in order 

what are you trying to share ? the first link is dead....

**Comment by andika207** [comment]
> I'm having trouble testing Microsoft Security Essentials for Windows XP.

don't be lazy and scroll a few topics down or use the search engine
there's been several discussions posts regarding the MSE issue

**Comment by stdin82** [comment]
> > install them in order
> 
> what are you trying to share ? the first link is dead....

Latest platform and definition updates that works for MSE on XP
all links are working, it's WU link

**Comment by kirb** [comment]
Closing in favor of #256 because there's a bit more info in that thread (thanks @stdin82!).
