### ISSUE TITLE
Make an option to download/use Legacy Update with the root certs and servicing stack updates offline.

### ISSUE THREAD

**Issue by ibay770** [LegacyUpdate/LegacyUpdate#211]
Sometimes, when trying to install older versions of win7 in VMware, VMware tools refuses to install because it needs the servicing stack updates. Without VMware tools, it can't connect to the internet to install said updates... So if its possible to add an option to download Legacy updates with just the certs and service stack, it can update it, and once internet access is restored, it'll do the rest.

[VMware message.](https://communities.vmware.com/t5/VMware-Workstation-Pro/Setup-failed-to-install-the-VSock-Virtual-Machine-Communication/td-p/2310468)

**Comment by kirb** [comment]
Closing this in favor of #107. Thanks for reporting!
