### ISSUE TITLE
Unable to run LegacyUpdate v1.9 due to illegal instruction

### ISSUE THREAD

**Issue by socram8888** [LegacyUpdate/LegacyUpdate#220]
Latest stable version cannot be even opened in non-Pro Pentium or Vortex86 machines, which have the i586 instruction set, due to some CMOV instructions (which were introduced in i686).

![Dibujo](https://github.com/kirb/LegacyUpdate/assets/515068/3087c8f0-cb74-4abb-8598-e56a4b903870)

**Comment by kirb** [comment]
Interesting... does Legacy Update 1.8 or 1.7 work? (You can download them directly in Internet Explorer on XP by changing the version in the download link)

Either 1.8 or 1.9 (probably 1.9, kinda forgetting now) was when I changed from building the setup using MakeNSIS on Windows, to building on Linux using the NSIS build packaged by Debian/Ubuntu. It's possible NSIS's official build has extra flags such as `-march=i486` to ensure later instructions aren't used, and [Debian/Ubuntu's](https://salsa.debian.org/debian/nsis/-/blob/debian/3.09-1/debian/rules) doesn't for some reason. Hopefully if that's the case, I can just copy the exehead stubs from the Windows build to fix this.

**Comment by socram8888** [comment]
1.8 does not open, it just crashes like before. 1.7.1 does work fine.

**Comment by smoix** [comment]
I confirm that it's broken on AMD K6 CPUs also, which are i586 and lack the CMOV instruction. 

I'm adding the Windows 2000 Event Viewer log, it lists illegal instruction. 

[error.txt](https://github.com/LegacyUpdate/LegacyUpdate/files/14653168/error.txt)

**Comment by SSUPII** [comment]
I actually was able to install Legacy Update 1.9 by temporarily booting from the hard drive on a Pentium II machine. This is of course not optimal, but once installed and put back in my Cyrix machine (#242) the service doesn't seem to have any issues.

**Comment by kirb** [comment]
Yep, switching hardware also works as a workaround. Specifically only the setup (and uninstaller) has this issue, while the main ActiveX dll will work back to a 486.

**Comment by XPbIM3** [comment]
Any other workarounds?   1.7.1 does not does any updates stating that 0 updates found.

**Comment by kirb** [comment]
Fixed in 1.10.
