### ISSUE TITLE
Wrong URL for WinXP/2K3 x64 MSE Definitions

### ISSUE THREAD

**Issue by AffSeda** [LegacyUpdate/LegacyUpdate#229]
On this page:
https://legacyupdate.net/faq/issues

It is linked:

Windows XP 64-bit Security Essentials:
(https://content.legacyupdate.net/definitionupdates.microsoft.com/download/DefinitionUpdates/VersionedSignatures/AM/1.291.2053.0/amd64/mpam-fe.exe) (1.265.826.0, 18 April 2018)

This file cannot install on Windows XP/2K3 x64.

But the correct link (which can install on WinXP x64 / Server 2003 x64) should be this:
https://content.legacyupdate.net/definitionupdates.microsoft.com/download/DefinitionUpdates/VersionedSignatures/AM/1.265.826.0/amd64/mpam-fe.exe

**Comment by kirb** [comment]
This was fixed a while ago, thanks for reporting.
