### ISSUE TITLE
Porting LU website to arm64

### ISSUE THREAD

**Issue by usefulstuffs** [LegacyUpdate/LegacyUpdate#235]
Because why not? It would be cool to mix modernicity of arm64 PCs with vintageness of the v6 Windows Update website.

**Comment by usefulstuffs** [comment]
Also pls port back Windows 10 upgrade for Windows 7/8.1 devices (a person got it delivered with WSUS and 2 registry values)

**Comment by stdin82** [comment]
Why don't you port it with the stolen WUIsBack?

**Comment by kirb** [comment]
@usefulstuffs, you were banned from the Discord because of ongoing poor behavior in this community. Please understand the ban applies here as well.

Closing as duplicate of #209.
