### ISSUE TITLE
AMD K6-2 /  LS 5MVP3 rev2.0  / windows XP SP3 VLK   -  unable to run legacyupdate

### ISSUE THREAD

**Issue by XPbIM3** [LegacyUpdate/LegacyUpdate#237]
AMD K6-2 / 256MB RAM/ S3 Trio 3D2x / LS 5MVP3 rev2.0  / windows XP SP3 VLK MSDN

Trying to run LegacyUpdate for windows xp ,   result in throwing an exception with code 0xc000001d

is there anything to do with lack of SSE instruction set?

**Comment by kirb** [comment]
Thanks for reporting! We're already tracking this as #220 so closing in favor of that. It’s an issue with Pentium-class CPUs, which lack some instructions the setup has been (unintentionally) compiled to expect.
