### ISSUE TITLE
Can't install legacy update Vista SP2 (Server execution failed)

### ISSUE THREAD

**Issue by WindClan** [LegacyUpdate/LegacyUpdate#238]
It fails to install the mandatory prerequisites (i already have them installed but it tries anyway)
It throws this error https://www.hresult.info/FACILITY_WINDOWS/0x80080005

**Comment by notbronwyn** [comment]
Apparently this only works with the SHA2 patch installed

**Comment by kirb** [comment]
Seems like this hasn't been reported otherwise so I'm going to close this, haven't been able to reproduce this myself. If you have time, you could maybe set up a new VM and figure out steps to reproduce the error, but no worries if that's too annoying.
