### ISSUE TITLE
Display more results after search

### ISSUE THREAD

**Issue by wyf180** [LegacyUpdate/LegacyUpdate#257]
Original Microsoft®Update Catalog could show 1000 results after search.However LegacyUpdate could only show 200 results.Could you fix the problem and could find more results by pages?
![nnnn](https://github.com/user-attachments/assets/2aa5e6fd-e779-40af-a8d7-610431135a2c)

**Comment by kirb** [comment]
Closing as duplicate of #156, but thanks for filing this. I'm rebuilding the download center backend currently, and this is one of the things I'll definitely fix.
