### ISSUE TITLE
Could "Activate Windows" function readd to LU?

### ISSUE THREAD

**Issue by sal-ammoniac** [LegacyUpdate/LegacyUpdate#259]
The function seems to be removed on Legacy Update 1.9.

Also ,Office XP and Office 2003 Retail/OEM seems to also have activation issue on Windows XP (Though their activation works fine on Windows 11), could it be added later?

**Comment by kirb** [comment]
The feature hasn’t been removed, although it checks if you need activation by looking for a running instance of `wpabaln.exe`, which handles the activation tray icon. I honestly should change this to do a proper activation check via WMI.

Haven’t looked into Office activation, but making that work again is something we should consider. I believe I did also have issues activating Office 2007 with a key I own, on Vista too, which should have alleviated at least some of the SSL problems.

**Comment by sal-ammoniac** [comment]
> The feature hasn’t been removed, although it checks if you need activation by looking for a running instance of `wpabaln.exe`, which handles the activation tray icon. That is _usually_ but may not always be running when XP is in its trial/grace period. I honestly should change this to do a proper activation check via WMI.
> 
> Haven’t looked into Office activation, but making that work again is something we should consider. I believe I did also have issues activating Office 2007 with a key I own, on Vista too, which should have alleviated at least some of the SSL problems.

The detection is really buggy. Even with wpabaln it will not show "Activate Windows" using 1.9 on my testing. 
![屏幕截图 2024-09-18 230253](https://github.com/user-attachments/assets/dde12c21-fd0f-464a-8965-9a80b32e4660)

**Comment by kirb** [comment]
Implemented in 0b5c3ea. XP doesn't support the documented method I was hoping to use, so I used the private licdll.dll there. That API is well-known for being used by activation cracks, so hopefully it doesn't cause antivirus false-positives…
