### ISSUE TITLE
Press "Download and Install Now" did not initiate update install on Windows XP

### ISSUE THREAD

**Issue by sal-ammoniac** [LegacyUpdate/LegacyUpdate#269]
![屏幕截图 2024-10-14 172059](https://github.com/user-attachments/assets/99ec9ed3-cd97-4a44-96b7-29ec22ab2958)

Legacy Update 1.10 is used and it is on a fresh installed Windows XP SP3 (IE6 uesd)

**Comment by Karabies** [comment]
Having this issue too, XP Pro SP3 x86 using IE6. Using Legacy Update 1.10

Clicking the button causes a page error to occur. Inspecting the page's code shows no obvious cause for the issue. Strangely it says KB898461 is downloaded and ready to install after I restarted to see if that would fix it.

![Screenshot_4465](https://github.com/user-attachments/assets/9bb6ac3b-12cf-498b-98b4-a20ac99743db)
![Screenshot_4466](https://github.com/user-attachments/assets/eca16eac-5907-4df0-97bb-c38ebdf1af76)
![Screenshot_4467](https://github.com/user-attachments/assets/7a753633-a44a-4b9c-b052-97e7c155bce5)

**Comment by kirb** [comment]
Thanks, I made another silly typo. Fixed now. You may need to ctrl-F5 or try again in 15-ish minutes if it still doesn't work.
