### ISSUE TITLE
Version 1.10 didn't activate my copy of Windows XP

### ISSUE THREAD

**Issue by 44cK3r** [LegacyUpdate/LegacyUpdate#275]

**Comment by kirb** [comment]
Could you please provide more info? What were you expecting to happen, and what happened instead?

**Comment by 44cK3r** [comment]
I was expecting it to activate my copy of Windows XP as the installer said but It didn't and the checkbox was ticked so I don't know what else I can say sorry

**Comment by kirb** [comment]
Legacy Update only gives you the ability to activate online like you might have done 10 years ago. You still need to enter a valid key that will be accepted by Microsoft's servers.

**Comment by 44cK3r** [comment]
The servers died years ago it's not a problem though I just used the tool I normally use to activate

**Comment by kirb** [comment]
The servers are still up, just not accessible from a clean install of XP. Legacy Update fixes that.

**Comment by 44cK3r** [comment]
Oh ok I'll keep using the tool then I click 3 buttons and I'm done a lot easier and a lot faster

**Comment by Trancer03** [comment]
Try this link: https://www.scribd.com/document/484031091/WINDOWS-XP-VISTA-SI-7-KEY-URI

**Comment by kirb** [comment]
@Trancer03 Thanks so much for helping out, but I’d rather we not condone piracy here. This is an old thread that was closed 4 months ago anyway.
