### ISSUE TITLE
Error 800A00D when clicking Install Updates

### ISSUE THREAD

**Issue by kirb** [LegacyUpdate/LegacyUpdate#291]
Error only happens when control is running unelevated. When elevated, no issues. Seems to only happen on Windows 8 and later.

## If you’re having this issue
To work around this: Find Legacy Update in the Start menu, then right-click and choose Run as Administrator.

Note that this will make the entire Internet Explorer window run as administrator. This isn’t very safe for regular web browsing. You should only use this IE window for Legacy Update, then close it afterwards.

**Comment by seba2282** [comment]
@kirb you need add install by Legacy Update:
 1. windows6.0-kb4019204
 2. windows6.0-kb4018271 after installation IE 9.0
 Then after that all start working windows update in Vista normally with legacy update

I tell again. Without that WU can't find updates on Vista.

**Comment by kirb** [comment]
@seba2282 This is unrelated to this issue. I worked around 800A00D on the server, it’s a bug in my code, not a WU problem.

I really appreciate you helping out, but you need to be patient. I saw your other comments, there’s no need to continually try getting my attention, especially by hijacking unrelated threads. The priority for the project right now is fixing regressions in 1.10, of which there are much more serious bugs like reboot loops. I can’t reproduce any issue with WU without those updates installed. Could you (in #281 and not here) provide more info on what this changes?

**Comment by seba2282** [comment]
I hope you have right. Because and in situation without that error, windows update was finding infinitely updates without that two updates. After install what i told, magic started come and faster all updates as found.
