### ISSUE TITLE
WUMT with WSUS fails after uninstalling LegacyUpdate

### ISSUE THREAD

**Issue by LimaXRomeo** [LegacyUpdate/LegacyUpdate#62]
I previously use Windows Update MiniTool on my Win2K workstation and set my Windows 11 pc as WSUS server. It worked totally fine.
I installed LegacyUpdate 1.4.1 in W2K and later uninstalled it. Then I restored my previous WSUS settings in the registry, but WUMT always fail to check for updates with error 0x80072EFD, and there's no incoming requests shown on my WSUS server's log. The same thing also happens in a Win2K virtual machine.

**Comment by Skywatcher17** [comment]
Same problem here.

**Comment by kirb** [comment]
Do you still experience this issue?

**Comment by LimaXRomeo** [comment]
This issue doesn't seem to exist in the latest version. Thank you all for your contribution.
